export default [
    {
        id: 1,
        title: 'Plenittá - Agência digital',
        alias: 'digital-agency',
        desc: 'Um projeto feito em WordPress e Elementor, criado para uma agência digital com design moderno e totalmente responsivo.',
        img: [
            '/src/images/projects/digital-agency/115-home-visivel-Plenittá.png',
            '/src/images/projects/digital-agency/114-home-full-Plenittá.png',
            '/src/images/projects/digital-agency/117-quem-somos-visivel-Plenittá.png',
            '/src/images/projects/digital-agency/116-quem-somos-full-Plenittá.png',
            '/src/images/projects/digital-agency/119-servicos-visivel-Plenittá.png',
            '/src/images/projects/digital-agency/118-servicos-full-Plenittá.png',
            '/src/images/projects/digital-agency/121-contato-visivel-Plenittá.png',
            '/src/images/projects/digital-agency/120-contato-full-Plenittá.png',
        ],
    },
    {
        id: 2,
        title: 'Architects - Site Portfolio',
        alias: 'architects',
        desc: 'Um projeto feito em HTML, Tailwind e JavaScript, criado para uma firma de arquitetura com design moderno e totalmente responsivo.',
        img: [
            '/src/images/projects/architects/034-home-visivel-architects.png',
            '/src/images/projects/architects/035-home-full-architects.png',
            '/src/images/projects/architects/036-galeria-visivel-architects.png',
            '/src/images/projects/architects/037-galeria-full-architects.png',
            '/src/images/projects/architects/038-servicos-visivel-architects.png',
            '/src/images/projects/architects/039-servicos-full-architects.png',
            '/src/images/projects/architects/040-sobre-nos-visivel-architects.png',
            '/src/images/projects/architects/041-sobre-nos-full-architects.png',
            '/src/images/projects/architects/042-contato-architects.png',
        ],
    },
    {
        id: 3,
        title: 'My Books App',
        alias: 'notes-app',
        desc: 'Aplicativo de design simples, desenvolvido com Node, TypeScript e React. O backend foi feito seguindo os estilos arquiteturais REST e Microsserviços. O desafio foi usar JSON Web Tokens para lidar com dados dos usuários de forma segura. O processo de desenvolvimento seguiu uma abordagem TDD.',
        repo: 'https://github.com/jvitoralb/my-books-app',
        img: [
            '/src/images/projects/notes-app/100-notesapp-welcome.png',
            '/src/images/projects/notes-app/101-notesapp-welcome-dark.png',
            '/src/images/projects/notes-app/104-notesapp-login.png',
            '/src/images/projects/notes-app/094-notesapp-home.png',
            '/src/images/projects/notes-app/096-notesapp-home-more-dark.png',
            '/src/images/projects/notes-app/097-notesapp-settings.png',
            '/src/images/projects/notes-app/098-notesapp-email-settings.png',
        ],
    },
    {
        id: 4,
        title: 'Biblioteca API',
        alias: 'library',
        desc: 'Uma REST API desenvolvida para a conclusão do Santander Bootcamp 2023. O objetivo foi simular operações de uma biblioteca, como registrar livros, usuários e emitir empréstimo de livros aos usuários registrados. A API foi desenvolvida na linguagem Java utilizando Spring Framework, e PostgreSQL.',
        repo: 'https://github.com/jvitoralb/dio-lab-rest-api',
        img: [
            '/src/images/projects/library/078-library-ui.png',
            '/src/images/projects/library/079-library-create-user.png',
            '/src/images/projects/library/080-library-create-book.png',
            '/src/images/projects/library/081-library-create-loan.png',
            '/src/images/projects/library/082-library-schemas.png',
        ],
    },
    {
        id: 5,
        title: 'Quality Assurance App',
        alias: 'qa-app',
        desc: 'Um aplicativo Full Stack, com design básico, hospedado na nuvem e construído com JavaScript. O objetivo era aplicar o TDD usando Chaijs, Nodejs, Express e MongoDB. A arquitetura backend foi desenvolvida seguindo o estilo Microsserviços, visando autonomia dos serviços e melhor escalabilidade.',
        repo: 'https://github.com/jvitoralb/quality-assurance-app',
        img: [
            '/src/images/projects/qa-app/061-qa-projects-home.png',
            '/src/images/projects/qa-app/062-qa-projects-converter-full.png',
            '/src/images/projects/qa-app/063-qa-projects-issues-tracker-full.png',
            '/src/images/projects/qa-app/064-qa-projects-personal-library-full.png',
            '/src/images/projects/qa-app/065-qa-projects-sudoku-solver-full.png',
            '/src/images/projects/qa-app/066-qa-projects-english-translator.png',
        ],
    },
    {
        id: 6,
        title: 'Análise de dados',
        alias: 'sa',
        desc: 'Uma aplicação Web Fullstack, desenvolvida com Vuejs e Nestjs, que faz a leitura de planilhas com a biblioteca Exceljs, e utiliza os dados para o cálculo de indicadores financeiros, e assim, demontrar os indicadores em gráficos construídos com D3.js. A aplicação foi desenvolvida em ambiente docker, onde o backend foi feito seguindo uma prática de TDD com Jest.',
        repo: 'https://github.com/jvitoralb/spreadsheet-analysis',
        img: [
            '/src/images/projects/sa/106-sa-analysis-page.png',
            '/src/images/projects/sa/109-sa-charts.png',
        ],
    },
];